[ids]
# In case the following mappings should only be applied to a specific device, list the exact HEX ID(s) instead of *.
# Example:
#   sudo keyd.rvaiya monitor
#   ...
#   Logitech USB Receiver	046d:c548:ee80da6c	f down
#   Logitech USB Receiver	046d:c548:ee80da6c	f up
#   ...
# Add the full device ID (e.g., 046d:c548:ee80da6c) to the ids section below.
*

# Define your custom key bindings layer
[meta_chord]
# These emit the virtual macros when pressed
# Choards: Super+/ > {key} -> Meta+Control+Alt+Shift+{key}
# For all common keys: a-z, 0-9, f1-f12, and some special keys like space, enter, etc.
# Note that not all combinations may work depending on the environment or application.
a = M-C-A-S-a
b = M-C-A-S-b
c = M-C-A-S-c
d = M-C-A-S-d
e = M-C-A-S-e
f = M-C-A-S-f
g = M-C-A-S-g
h = M-C-A-S-h
i = M-C-A-S-i
j = M-C-A-S-j
k = M-C-A-S-k
l = M-C-A-S-l
m = M-C-A-S-m
n = M-C-A-S-n
o = M-C-A-S-o
p = M-C-A-S-p
q = M-C-A-S-q
r = M-C-A-S-r
s = M-C-A-S-s
t = M-C-A-S-t
u = M-C-A-S-u
v = M-C-A-S-v
w = M-C-A-S-w
x = M-C-A-S-x
y = M-C-A-S-y
z = M-C-A-S-z

0 = M-C-A-S-0
1 = M-C-A-S-1
2 = M-C-A-S-2
3 = M-C-A-S-3
4 = M-C-A-S-4
5 = M-C-A-S-5
6 = M-C-A-S-6
7 = M-C-A-S-7
8 = M-C-A-S-8
9 = M-C-A-S-9

f1 = M-C-A-S-f1
f2 = M-C-A-S-f2
f3 = M-C-A-S-f3
f4 = M-C-A-S-f4
f5 = M-C-A-S-f5
f6 = M-C-A-S-f6
f7 = M-C-A-S-f7
f8 = M-C-A-S-f8
f9 = M-C-A-S-f9
f10 = M-C-A-S-f10
f11 = M-C-A-S-f11
f12 = M-C-A-S-f12

space = M-C-A-S-space
enter = M-C-A-S-enter
tab = M-C-A-S-tab
esc = M-C-A-S-esc
backspace = M-C-A-S-backspace
delete = M-C-A-S-delete
insert = M-C-A-S-insert
home = M-C-A-S-home
end = M-C-A-S-end
pageup = M-C-A-S-pageup
pagedown = M-C-A-S-pagedown
up = M-C-A-S-up
down = M-C-A-S-down
left = M-C-A-S-left
right = M-C-A-S-right

minus = M-C-A-S-minus
equal = M-C-A-S-equal
leftbrace = M-C-A-S-leftbrace
rightbrace = M-C-A-S-rightbrace
backslash = M-C-A-S-backslash
semicolon = M-C-A-S-semicolon
apostrophe = M-C-A-S-apostrophe
comma = M-C-A-S-comma
dot = M-C-A-S-dot
slash = M-C-A-S-slash
grave = M-C-A-S-grave
print = M-C-A-S-print
pause = M-C-A-S-pause
menu = M-C-A-S-menu

# Hook into the native Super (meta) modifier layer
[meta]
# If Super+/ is tapped, switch to meta_chord layer for exactly one keystroke.
#w = oneshot(meta_chord)
# Timeout after 1sec (1000ms) if no key is pressed after Super+/, or if a key is pressed that isn't defined in meta_chord.
#x = timeout(oneshot(meta_chord), 1000, M-x)
slash = timeout(oneshot(meta_chord), 1000, M-slash)

