#!/bin/sh
# -*- mode: sh; sh-shell: sh; indent-tabs-mode: nil; tab-width: 2 -*-
# vim: ft=sh:et:ts=2:sts=2:sw=2
# code: language=sh insertSpaces=true tabSize=2
# shellcheck shell=sh
#
# nordvpnd ExecStartPost hook: re-enable IPv6 after NordVPN daemon disables it.
#
# NordVPN 5.x unconditionally sets net.ipv6.conf.*.disable_ipv6=1 at daemon
# startup with no CLI option to override this. The sleep gives nordvpnd time
# to complete its init (and apply its sysctl changes) before we restore them.
#
# Install:
#   install -m 755 nordvpn-restore-ipv6 /usr/local/bin/nordvpn-restore-ipv6
#
#   /etc/systemd/system/nordvpnd.service.d/restore-ipv6.conf:
#     [Service]
#     ExecStartPost=/usr/local/bin/nordvpn-restore-ipv6
#
#   systemctl daemon-reload

sleep 2

sysctl -w net.ipv6.conf.all.disable_ipv6=0 net.ipv6.conf.default.disable_ipv6=0

for f in /proc/sys/net/ipv6/conf/*/disable_ipv6; do
  echo 0 > "${f}"
done
