conky.config = {
    xinerama_head = 2,
    alignment = 'top_left',
    background = false,
    border_width = 0,
    color1 = '#FFFFFF',
    color2 = '#6a7d93',
    color3 = '#0077FF',
    color4 = '#FFD000',
    default_color = '#FFFFFF',
    default_outline_color = '#000000',
    default_shade_color = '#6a7d93',
    cpu_avg_samples = 1,
    double_buffer = true,
    draw_borders = false,
    draw_graph_borders = true,
    draw_outline = false,
    draw_shades = false,
    gap_x = 1010,
    gap_y = 10,
    border_outer_margin = 0,
    max_port_monitor_connections = 64,
    maximum_width = 470,
    minimum_width = 470,
    max_user_text = 16384,
    minimum_height = 480,
    net_avg_samples = 2,
    no_buffers = true,
    out_to_console = false,
    out_to_x = false,
    out_to_wayland = true,
    own_window = true,
    own_window_class = 'Conky',
    own_window_type = 'dock',
    own_window_hints = 'undecorated,below,sticky,skip_taskbar,below',
    own_window_transparent = yes,
    own_window_argb_value = 200,
    own_window_colour = 'black',
    own_window_argb_visual = true,
    update_interval = 5,
    top_cpu_separate = true,
    top_name_width = 13,
    uppercase = false,
    use_xft = true,
    xftalpha = 0.8,
    font = 'FiraCode Nerd Font:size=9:regular',
    font1 = 'FiraCode Nerd Font:size=9:bold',
    font3 = 'FiraCode Nerd Font:bold:size=10'
};

conky.text = [[
${color3}${font3}NETWORK INTERFACES${font}${color}

${color1}${font1}Interface:${font} ${color}wlp14s0 (WiFi 6/7)
${color1}${font1}Download:${font}  ${color}${downspeed wlp14s0} ${goto 235}${font1}Upload:${font} ${upspeed wlp14s0}
${color3}${downspeedgraph wlp14s0 60,470 07CC0D FF0000 -t} ${goto 235}${upspeedgraph wlp14s0 60,225 07CC0D FF0000 -t}

${color1}${font1}Interface:${font} ${color}enp7s0 (2.5/5 GbE to saito-local)
${color1}${font1}Download:${font}  ${color}${downspeed enp7s0} ${goto 235}${font1}${font1}Upload:${font} ${upspeed enp7s0}
${color1}${downspeedgraph enp7s0 60,470 07CC0D FF0000 -t} ${goto 235}${upspeedgraph enp7s0 60,225 07CC0D FF0000 -t}
${color2}${hr 2}${color}
${color3}${font3}TCP CONNECTIONS${font}${color}

${color1}${font1}Remote Service/Port ${alignr}Outbound Connections:${font} ${color}${tcp_portmon 32768 61000 count}
${tcp_portmon 32768 61000 rservice 0} ${alignr} ${tcp_portmon 32768 61000 rhost 0}
${tcp_portmon 32768 61000 rservice 1} ${alignr} ${tcp_portmon 32768 61000 rhost 1}
${tcp_portmon 32768 61000 rservice 2} ${alignr} ${tcp_portmon 32768 61000 rhost 2}
${tcp_portmon 32768 61000 rservice 3} ${alignr} ${tcp_portmon 32768 61000 rhost 3}
${tcp_portmon 32768 61000 rservice 4} ${alignr} ${tcp_portmon 32768 61000 rhost 4}
${tcp_portmon 32768 61000 rservice 5} ${alignr} ${tcp_portmon 32768 61000 rhost 5}
${tcp_portmon 32768 61000 rservice 6} ${alignr} ${tcp_portmon 32768 61000 rhost 6}
${tcp_portmon 32768 61000 rservice 7} ${alignr} ${tcp_portmon 32768 61000 rhost 7}
${tcp_portmon 32768 61000 rservice 8} ${alignr} ${tcp_portmon 32768 61000 rhost 8}
${tcp_portmon 32768 61000 rservice 9} ${alignr} ${tcp_portmon 32768 61000 rhost 9}

${color1}${font1}Local Service/Port ${alignr}Inbound Connections:${font} ${color}${tcp_portmon 1 32767 count}
${tcp_portmon 1 32767 lservice 0} ${alignr} ${tcp_portmon 1 32767 rhost 0}
${tcp_portmon 1 32767 lservice 1} ${alignr} ${tcp_portmon 1 32767 rhost 1}
${tcp_portmon 1 32767 lservice 2} ${alignr} ${tcp_portmon 1 32767 rhost 2}
${tcp_portmon 1 32767 lservice 3} ${alignr} ${tcp_portmon 1 32767 rhost 3}
${tcp_portmon 1 32767 lservice 4} ${alignr} ${tcp_portmon 1 32767 rhost 4}
${tcp_portmon 1 32767 lservice 5} ${alignr} ${tcp_portmon 1 32767 rhost 5}
]];
