#!/bin/sh
# ~/.xsession.d/batou: custom xsession for host batou
# code: language=bash insertSpaces=true tabSize=2
# keywords: zsh bash dotfile xsession shell shell-script x11
# author: Andreas Weyer

# disable dell touchpad (get id via: xinput list)
xinput --disable 14

# start synregy server
synregys

# delete previous log file
rm -f ~/i3.log 2>&1 >/dev/null

# run i3 windowmanager
exec i3 -V >> ~/i3.log 2>&1
