#!/bin/sh
# ~/.xsession.d/batou: custom xsession for host batou

# Author:   cbaoth <dev@cbaoth.de>
# Keywords: dotfile xorg

# disable dell touchpad (get id via: xinput list)
xinput --disable 14

# start synregy server
synregys

# delete previous log file
rm -f ~/i3.log 2>&1 >/dev/null

# run i3 windowmanager
exec i3 -V >> ~/i3.log 2>&1
