#!/bin/sh
# ~/.xsession.d/saito: custom xsession for host saito
# code: language=bash insertSpaces=true tabSize=2
# keywords: zsh bash dotfile xsession shell shell-script x11
# author: Andreas Weyer

# turn off screen blacking
# since tv will switches to cable mode (bad) and has its own energy save timer
xset s off
xset -dpms
xset dpms 0 0 0

# enable "natural scrolling" (invert) on logitech touch pad
xinput  set-prop "pointer:Logitech K400" 299 1

# use qt5ct theme (if installed)
command -v qt5ct && export QT_QPA_PLATFORMTHEME=qt5ct

# run stuff
runbg barrierc --enable-crypto -d ERROR puppet
runbg /bin/teamviewer
runbg ~/jd2/JDownloader2
runbg x11vnc -auth guess -forever -loop -noxdamage -repeat -rfbauth /home/cbaoth/.vnc/passwd -rfbport 5900 -shared

# delete previous log file
rm -f ~/i3.log 2>&1 >/dev/null
# run i3 windowmanager
#exec i3 -V >> ~/i3.log 2>&1
# run gnome
exec gnome-session
