#!/bin/sh
# ~/.xsession.d/saito: custom xsession for host saito

# Author:   cbaoth <dev@cbaoth.de>
# Keywords: dotfile xorg

# turn off screen blacking
# since tv will switches to cable mode (bad) and has its own energy save timer
xset s off
xset -dpms
xset dpms 0 0 0

# enable "natural scrolling" (invert) on logitech touch pad
xinput  set-prop "pointer:Logitech K400" 299 1

# use qt5ct theme (if installed)
command -v qt5ct && export QT_QPA_PLATFORMTHEME=qt5ct

# run stuff
barrierc --enable-crypto -d ERROR puppet

# delete previous log file
rm -f ~/i3.log 2>&1 >/dev/null
# run i3 windowmanager
exec i3 -V >> ~/i3.log 2>&1

