#!/usr/bin/env bash
# -*- mode: sh; sh-shell: bash; indent-tabs-mode: nil; tab-width: 2 -*-
# vim: ft=bash:et:ts=2:sts=2:sw=2
# code: language=bash insertSpaces=true tabSize=2
# shellcheck shell=bash
#
# Make the bedtime-shutdown files immutable (chattr +i). Thin wrapper around
# bedtime-rearm.sh --lock. The next re-arm also re-locks when
# BSS_REARM_ENFORCE_IMMUTABLE=true.

exec /opt/bin/bedtime-rearm.sh --lock "$@"
