#!/usr/bin/env bash
# -*- mode: sh; sh-shell: bash; indent-tabs-mode: nil; tab-width: 2 -*-
# vim: ft=bash:et:ts=2:sts=2:sw=2
# code: language=bash insertSpaces=true tabSize=2
# shellcheck shell=bash
#
# ~/.xsession.d/batou: host-specific xsession commands for batou.

# Log to file for debugging and monitoring (e.g. conky)
XSESSION_LOG_FILE="$HOME/.xsession.log"
# Overwrite instead of append to avoid huge log files (no need for log rotation)
exec > >(tee "$XSESSION_LOG_FILE") 2>&1

# disable dell touchpad (get id via: xinput list)
xinput --disable 14

# start synregy server
synregys

# delete previous log file
rm -f ~/i3.log 2>&1 >/dev/null

# run i3 windowmanager
exec i3 -V
