#!/usr/bin/env sh
# -*- mode: sh; sh-shell: sh; indent-tabs-mode: nil; tab-width: 2 -*-
# vim: ft=sh:et:ts=2:sts=2:sw=2
# code: language=sh insertSpaces=true tabSize=2
# shellcheck shell=sh
#
# ~/.xsession.d/batou: host-specific xsession commands for batou.

# disable dell touchpad (get id via: xinput list)
xinput --disable 14

# start synregy server
synregys

# delete previous log file
rm -f ~/i3.log 2>&1 >/dev/null

# run i3 windowmanager
exec i3 -V >> ~/i3.log 2>&1
