#!/usr/bin/env bash
# -*- mode: sh; sh-shell: bash; indent-tabs-mode: nil; tab-width: 2 -*-
# vim: ft=bash:et:ts=2:sts=2:sw=2
# code: language=bash insertSpaces=true tabSize=2
# shellcheck shell=bash
#
# ~/.xsession.d/default: default session executed by .xinitrc

# Log to file for debugging and monitoring (e.g. conky)
XSESSION_LOG_FILE="$HOME/.xsession.log"
# Overwrite instead of append to avoid huge log files (no need for log rotation)
exec > >(tee "$XSESSION_LOG_FILE") 2>&1

# activate xorg composite shadow and transparence stuff
#runbg xcompmgr -cCfF -D6
#runbg xcompmgr -cCfF -t-5 -l-5 -r4.2 -o.55 -D6
#runbg compton -cCfF -D6

# run windowmanager
exec i3 -V
#exec fluxbox
## or if you want to keep a log:
# exec fluxbox -log "$HOME/.fluxbox/log"

#pwm ion3 openbox metacity gnome-session enlightenment fluxbox
#blackbox evilwm wmiiwm
#exec ssh-agent sh -c "ssh-add </dev/null && exec fluxbox"
#exec ssh-agent sh -c "ssh-add </dev/null && exec lxsession"
#exec ssh-agent sh -c "ssh-add </dev/null && exec xmonad"
#ssh-agent sh -c "ssh-add </dev/null && exec fluxbox" & wmpid=$!
#exec ssh-agent sh -c "ssh-add </dev/null && exec pwm"
#exec ssh-agent sh -c "ssh-add </dev/null && exec ion3"
#exec ssh-agent sh -c "ssh-add </dev/null && exec fluxbox"
#exec ssh-agent sh -c "ssh-add </dev/null && exec gnome-session"

# hang point (wait for wm to exit)
#wait $wmpid

# restore fontpath
#xset fp default
