#!/usr/bin/env bash
# -*- mode: sh; sh-shell: bash; indent-tabs-mode: nil; tab-width: 2 -*-
# vim: ft=bash:et:ts=2:sts=2:sw=2
# code: language=bash insertSpaces=true tabSize=2
# shellcheck shell=bash
#
# ~/.xsession.d/saito: host-specific xsession commands for saito.

# Log to file for debugging and monitoring (e.g. conky)
XSESSION_LOG_FILE="$HOME/.xsession.log"
# Overwrite instead of append to avoid huge log files (no need for log rotation)
exec > >(tee "$XSESSION_LOG_FILE") 2>&1

# turn off screen blacking
# since tv will switches to cable mode (bad) and has its own energy save timer
xset s off
xset -dpms
xset dpms 0 0 0

# enable "natural scrolling" (invert) on logitech touch pad
xinput  set-prop "pointer:Logitech K400" 299 1

# use qt5ct theme (if installed)
command -v qt5ct && export QT_QPA_PLATFORMTHEME=qt5ct

# run stuff
runbg barrierc --enable-crypto -d ERROR puppet
runbg /bin/teamviewer
runbg ~/jd2/JDownloader2
runbg x11vnc -auth guess -forever -loop -noxdamage -repeat -rfbauth /home/cbaoth/.vnc/passwd -rfbport 5900 -shared

# run i3 windowmanager
exec i3 -V
# run gnome
#exec gnome-session
